### ISSUE TITLE
Position from g-code

### ISSUE THREAD

**Issue by haniehes** [glumb/mrc#4]
Hi, 
I am working with UR5 as a 6DOF robot and I connect to UR_modern driver trough ROS Kinetic. Actually, I need to translate a g-code file to robot positions. Hence, I tried to find out your g-code insertion method in order to combine it with my robot controller, but I couldn't distinguish it. I would be thankful if you could make this step of your program (g-code interpreting) more clear?

**Comment by glumb** [comment]
In the context of MRC the g-code is called MRIL (for MicroPede Robot Instruction Language). Therefore the g-code/MRIL parsing can be found in https://github.com/glumb/mrc/blob/master/src/MRILParser.cpp 
The instructions are parsed char by char and the respective  methods are triggered.
I attached a schema of the controller. I hope this helps.

![mrc](https://user-images.githubusercontent.com/3062564/32168766-1e3b6806-bd6e-11e7-9931-1864f9b8b8b8.png)

**Comment by haniehes** [comment]
Thanks for your fast response. I will try it.

**Comment by matteopantano** [comment]
Hey @haniehes were you able to do the integration for the UR? Would you mind share the final outcome?
Thanks!
