### ISSUE TITLE
Better explanation of Geometry array

### ISSUE THREAD

**Issue by TadyTheFish** [glumb/mrc#5]
Can you please better explain what do the values in the geometry array present.

`float geometry[5][3] = {
    {  4.2, 0,   8.5 },
    {    0, 0,   9.5 },
    {    1, 0,  1.85 },
    { 14.8, 0,     0 },
    {    0, 0,  -2.2 }
};`
Thank you!

**Comment by glumb** [comment]
Those are the coordinates of the links V0-V5 according to the schematic below.

```C
float geometry[5][3] = { 
 { 4.2, 0, 8.5 }, //V0 {x,y,z}
 { 0, 0, 9.5 }, //V1
 { 1, 0, 1.85 }, //V2
 { 14.8, 0, 0 }, //V3
 { 0, 0, -2.2 } //V4
};
```

<img width="729" alt="bc6a01d0-3967-11e7-83c9-d572eef1bd12" src="https://user-images.githubusercontent.com/3062564/37585876-cf49250c-2b5a-11e8-9539-713608ee5cb7.png">

**Comment by TadyTheFish** [comment]
Thank you for the reply but there i can see the world coordiante system and
tool coordinate system. How do you define for example the V1 if it is long
200mm and pinting up (like the picture) is it x0,y0,z200?

And the V2 and V3 lenghts. How do I input if I have only V2 and is 100mm
long. Do I write x100,y0,z0?
What if the j3 is on j2? Can i use zero for V3?

Sorry for stupid questions:)
Thank you!

V pon., 19. mar. 2018 09:51 je oseba Maximilian Beck <
notifications@github.com> napisala:

**Comment by glumb** [comment]
I would kindly ask you to read my answer on GitHub. I editet it 5s after initial post. Maybe you did not receive the updated version.

**Comment by TadyTheFish** [comment]
Thank you! Got it working:)
