### ISSUE TITLE
Config for R-C

### ISSUE THREAD

**Issue by bytebang** [glumb/mrc#6]
Is there any configuration for the [mp-robot-c](https://micropede.de/shop/mp-robot-c) wich can be used out-of-the-box (like with the https://github.com/glumb/mrc/blob/master/config/mp-robot-d.h) ?

If yes - can you please uplad it to this repository ?

**Comment by glumb** [comment]
Its not available, unfortunately. The thing with the r-c is that you have to sync the additional axis on joint 1, but in reverse direction.
To sync the additional servo you could modify the main.cpp line 127 to something like this:

```
VarSpeedServo secondAxis1Servo(20, 150 * DEG_TO_RAD,  852, 2091,  -90 * DEG_TO_RAD,  90 * DEG_TO_RAD, 0);

void updateServos() {
    for (size_t i = 0; i < 8; i++) {
        servos[i]->process(updateServosEveryMs);
    }

    // sync second servo 
    secondAxis1Servo.setTargetRadAngle(servos[1]->getTargetRadAngle());
    secondAxis1Servo.setCurrentAngleVelocity(servos[1]->getCurrentAngleVelocity());
    secondAxis1Servo.process(updateServosEveryMs);
}
```

Basically configuring the additional servo and setting the angle to the same as the one which is usually used.
